import Dashbord from '../Components/Sidebar/Images/Dashboard.svg';
import Resources from '../Components/Sidebar/Images/Resources.svg';
import Settings from '../Components/Sidebar/Images/Settings.svg';
import DocsLogo from '../Components/ResourceModules/Image/DocsLogo.svg';
import PDFsLogo from '../Components/ResourceModules/Image/PDFsLogo.svg';
import SheetsLogo from '../Components/ResourceModules/Image/XlsLogo.svg';
import AudioLogo from '../Components/ResourceModules/Image/AudiosLogo.svg';
import VideoLogo from '../Components/ResourceModules/Image/VideosLogo.svg';

export const Json = [
  { Image: Dashbord, Title: 'Dashboard', src: '/dashboard' },
  { Image: Resources, Title: 'Resources', src: '/resource' },
  { Image: Settings, Title: 'Settings', src: '/settings' },
];
export const Logindata = [{ UserName: 'Alex Daubert', Member: 'Team Member' }];
export const ResourcesData = [
  { Image: DocsLogo, ResourcesType: 'Docs', TotalAvilable: '12' },
  { Image: SheetsLogo, ResourcesType: 'Sheets', TotalAvilable: '34' },
  { Image: PDFsLogo, ResourcesType: 'PDFs', TotalAvilable: '18' },
  { Image: AudioLogo, ResourcesType: 'Audios', TotalAvilable: '09' },
  { Image: VideoLogo, ResourcesType: 'Videos', TotalAvilable: '7' },
];
export const ResourcesFiles = [
  {
    No: '01',
    FileName: 'Best practices in leading remote teams',
    UplodedDate: '22/7/2023',
    Size: '100 KB',
    AccessType: 'View',
    DocType: PDFsLogo,
  },
  {
    No: '01',
    FileName: 'Result access email templates',
    UplodedDate: '02/5/2023',
    Size: '2.00 MB',
    AccessType: 'View',
    DocType: PDFsLogo,
  },
  {
    No: '02',
    FileName: 'Time sheet format',
    UplodedDate: '22/7/2023',
    Size: '100 KB',
    AccessType: 'View',
    DocType: SheetsLogo,
  },
  {
    No: '02',
    FileName: 'Company Policies',
    UplodedDate: '22/7/2023',
    Size: '100 KB',
    AccessType: 'View',
    DocType: DocsLogo,
  },
  {
    No: '03',
    FileName: 'HR Policy',
    UplodedDate: '22/7/2023',
    Size: '100 KB',
    AccessType: 'View',
    DocType: VideoLogo,
  },
  {
    No: '01',
    FileName: 'Best practices in leading remote teams',
    UplodedDate: '22/7/2023',
    Size: '100 KB',
    AccessType: 'View',
    DocType: PDFsLogo,
  },
  {
    No: '01',
    FileName: 'Result access email templates',
    UplodedDate: '02/5/2023',
    Size: '2.00 MB',
    AccessType: 'View',
    DocType: PDFsLogo,
  },
  {
    No: '02',
    FileName: 'Time sheet format',
    UplodedDate: '22/7/2023',
    Size: '100 KB',
    AccessType: 'View',
    DocType: SheetsLogo,
  },
  {
    No: '02',
    FileName: 'Company Policies',
    UplodedDate: '22/7/2023',
    Size: '100 KB',
    AccessType: 'View',
    DocType: DocsLogo,
  },
  {
    No: '03',
    FileName: 'HR Policy',
    UplodedDate: '22/7/2023',
    Size: '100 KB',
    AccessType: 'View',
    DocType: VideoLogo,
  },
  {
    No: '01',
    FileName: 'Best practices in leading remote teams',
    UplodedDate: '22/7/2023',
    Size: '100 KB',
    AccessType: 'View',
    DocType: PDFsLogo,
  },
  {
    No: '01',
    FileName: 'Result access email templates',
    UplodedDate: '02/5/2023',
    Size: '2.00 MB',
    AccessType: 'View',
    DocType: PDFsLogo,
  },
  {
    No: '02',
    FileName: 'Time sheet format',
    UplodedDate: '22/7/2023',
    Size: '100 KB',
    AccessType: 'View',
    DocType: SheetsLogo,
  },
  {
    No: '02',
    FileName: 'Company Policies',
    UplodedDate: '22/7/2023',
    Size: '100 KB',
    AccessType: 'View',
    DocType: DocsLogo,
  },
  {
    No: '03',
    FileName: 'HR Policy',
    UplodedDate: '22/7/2023',
    Size: '100 KB',
    AccessType: 'View',
    DocType: VideoLogo,
  },
  {
    No: '01',
    FileName: 'Best practices in leading remote teams',
    UplodedDate: '22/7/2023',
    Size: '100 KB',
    AccessType: 'View',
    DocType: PDFsLogo,
  },
  {
    No: '01',
    FileName: 'Result access email templates',
    UplodedDate: '02/5/2023',
    Size: '2.00 MB',
    AccessType: 'View',
    DocType: PDFsLogo,
  },
  {
    No: '02',
    FileName: 'Time sheet format',
    UplodedDate: '22/7/2023',
    Size: '100 KB',
    AccessType: 'View',
    DocType: SheetsLogo,
  },
  {
    No: '02',
    FileName: 'Company Policies',
    UplodedDate: '22/7/2023',
    Size: '100 KB',
    AccessType: 'View',
    DocType: DocsLogo,
  },
];
export const Userdata = [
  {
    gender: 'male',
    name: { title: 'Mr', first: 'Elio', last: 'Petit' },
    location: {
      street: { number: 5699, name: 'Rue de Cuire' },
      city: 'Metz',
      state: 'Var',
      country: 'France',
      postcode: 51298,
      coordinates: { latitude: '-21.3013', longitude: '-70.5371' },
      timezone: {
        offset: '+1:00',
        description: 'Brussels, Copenhagen, Madrid, Paris',
      },
    },
    email: 'elio.petit@example.com',
    designation: 'Member',
    login: {
      uuid: '3c7977f7-a3f9-40af-bbc9-a895cb2f06e5',
      username: 'smallmeercat678',
      password: 'quest1',
      salt: 'Nn7JbP7R',
      md5: 'faa994044f469af04f9cd476e8fa2208',
      sha1: '9b420eb674cb2c39c1fbcb4aebc9117611925ea4',
      sha256:
        'ff685adeb8fd9fb234eb00cd0b3c16364573a3c6fac3f115abb606f57694783c',
    },
    dob: { date: '1976-05-21T15:11:43.943Z', age: 47 },
    registered: { date: '2014-01-20T10:14:43.532Z', age: 9 },
    phone: '04-71-90-48-33',
    cell: '06-07-65-01-11',
    id: { name: 'INSEE', value: '1760440224620 92' },
    picture: {
      large: 'https://randomuser.me/api/portraits/men/35.jpg',
      medium: 'https://randomuser.me/api/portraits/med/men/35.jpg',
      thumbnail: 'https://randomuser.me/api/portraits/thumb/men/35.jpg',
    },
    nat: 'FR',
  },

  {
    gender: 'male',
    name: { title: 'Mr', first: 'Alexander', last: 'Campbell' },
    location: {
      street: { number: 2633, name: 'Tecumseh Rd' },
      city: 'Hudson',
      state: 'Nunavut',
      country: 'Canada',
      postcode: 'S6M 8U6',
      coordinates: { latitude: '-72.5622', longitude: '-74.1504' },
      timezone: { offset: '-10:00', description: 'Hawaii' },
    },
    email: 'alexander.campbell@example.com',
    designation: 'Leader',
    login: {
      uuid: '0214e69c-0867-45d1-a165-8b0bfc66b74d',
      username: 'happyfrog569',
      password: 'aaaa',
      salt: 'bIyDv2eQ',
      md5: '31542f802a4eebf722b14d75687505bc',
      sha1: '00def82054e3b99f57c069ea875b831b6a1ab2e1',
      sha256:
        '30f274de63ef56048a46e5ef73620068be825182ea37aa17348d3cb04d704504',
    },
    dob: { date: '1986-06-26T05:55:11.774Z', age: 36 },
    registered: { date: '2002-08-03T02:23:51.024Z', age: 20 },
    phone: 'Z74 K74-2873',
    cell: 'O85 P98-8556',
    id: { name: 'SIN', value: '816216899' },
    picture: {
      large: 'https://randomuser.me/api/portraits/men/70.jpg',
      medium: 'https://randomuser.me/api/portraits/med/men/70.jpg',
      thumbnail: 'https://randomuser.me/api/portraits/thumb/men/70.jpg',
    },
    nat: 'CA',
  },
];
